# /server/Dockerfile-deploy
FROM python:3.10

RUN apt-get -y update
RUN apt-get -y install vim

RUN mkdir /server
RUN mkdir /ssl
ADD . /server

WORKDIR /server

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python3 manage.py makemigrations --settings=config.settings.deploy
RUN python3 manage.py migrate --settings=config.settings.deploy
RUN python3 manage.py collectstatic  --noinput --settings=config.settings.deploy

EXPOSE 8005
CMD ["gunicorn", "--bind", "0.0.0.0:8005", "config.wsgi.deploy:application"]