version: '3'
services:
 nginx:
  image: nginx:latest
  ports:
   - "8000:8000"
  volumes:
   - ./nginx/local:/etc/nginx/conf.d
  depends_on:
   - web
 web:
  build:
    context: .
    dockerfile: Dockerfile-local
  volumes:
   - static-data:/server/static
volumes:
 static-data: