version: '3'
services:
 nginx:
  image: nginx:latest
  ports:
   - "8001:8001"
  volumes:
   - ./nginx/dev:/etc/nginx/conf.d
  depends_on:
   - web
 web:
  build:
    context: .
    dockerfile: Dockerfile-develop
  volumes:
   - static-data:/server/static
volumes:
 static-data: