version: '3'
services:
 nginx:
  image: nginx:latest
  ports:
   - "8005:8005"
  volumes:
   - ./nginx/deploy:/etc/nginx/conf.d
  depends_on:
   - web
 web:
  build:
    context: .
    dockerfile: Dockerfile-deploy
  volumes:
   - static-data:/server/static
volumes:
 static-data: